name: KMM Bridge/iOS Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
jobs:
  call-kmmbridge-publish:
    uses: hxxyyangyong/KMMBridgeGithubWorkflow/.github/workflows/KMMBridge-publish.yml
    secrets:
      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}